### ISSUE TITLE
Not capturing negative values

### ISSUE THREAD

**Issue by ikkemaniac** [Arisamiga/Advent-Of-Code-2022#1]
https://github.com/Arisamiga/Advent-Of-Code-2022/blob/654faa7b34fc83b22e34e0495076330240a79aec/Days/15/part1.py#L17-L20

You're not capturing the - of the negative values.
Took me quit a bit of time to understand what went wrong (i'm using your solutions to validate my answers before submitting ;)), hope i can save u some time.

**Comment by Arisamiga** [comment]
> https://github.com/Arisamiga/Advent-Of-Code-2022/blob/654faa7b34fc83b22e34e0495076330240a79aec/Days/15/part1.py#L17-L20
> 
> You're not capturing the - of the negative values. Took me quit a bit of time to understand what went wrong (i'm using your solutions to validate my answers before submitting ;)), hope i can save u some time.

Oh Oops! I didn't realize that it didn't capture the negative values. Thanks for letting me know 🙂 

I fixed the issue with https://github.com/Arisamiga/Advent-Of-Code-2022/commit/28f951c14e57f7587d4c6419dbcace329215fb10
